/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.glam.bff.openapi.wardrobe.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.glam.bff.openapi.wardrobe.model.GarmentPhotoDAO;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.annotation.Nullable;

/**
 * GarmentDAO
 */
@JsonPropertyOrder({
  GarmentDAO.JSON_PROPERTY_GARMENT_ID,
  GarmentDAO.JSON_PROPERTY_PHOTO,
  GarmentDAO.JSON_PROPERTY_USER_ID,
  GarmentDAO.JSON_PROPERTY_TITLE,
  GarmentDAO.JSON_PROPERTY_DESCRIPTION,
  GarmentDAO.JSON_PROPERTY_CATEGORY,
  GarmentDAO.JSON_PROPERTY_SUB_CATEGORY,
  GarmentDAO.JSON_PROPERTY_MAIN_COLOR,
  GarmentDAO.JSON_PROPERTY_SECOND_COLOR,
  GarmentDAO.JSON_PROPERTY_PATTERN,
  GarmentDAO.JSON_PROPERTY_BRAND,
  GarmentDAO.JSON_PROPERTY_IS_FAVORITE,
  GarmentDAO.JSON_PROPERTY_FABRIC,
  GarmentDAO.JSON_PROPERTY_CONDITION,
  GarmentDAO.JSON_PROPERTY_SLEEVE_LENGTH,
  GarmentDAO.JSON_PROPERTY_LENGTH,
  GarmentDAO.JSON_PROPERTY_SIZE_ENUM,
  GarmentDAO.JSON_PROPERTY_PATTERN_DETAIL,
  GarmentDAO.JSON_PROPERTY_SEASON,
  GarmentDAO.JSON_PROPERTY_STYLES,
  GarmentDAO.JSON_PROPERTY_PHOTO_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-19T16:15:08.532396+01:00[Europe/Rome]")
public class GarmentDAO {
  public static final String JSON_PROPERTY_GARMENT_ID = "garmentId";
  private String garmentId;

  public static final String JSON_PROPERTY_PHOTO = "photo";
  private GarmentPhotoDAO photo;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private String category;

  public static final String JSON_PROPERTY_SUB_CATEGORY = "subCategory";
  private String subCategory;

  public static final String JSON_PROPERTY_MAIN_COLOR = "mainColor";
  private String mainColor;

  public static final String JSON_PROPERTY_SECOND_COLOR = "secondColor";
  private String secondColor;

  public static final String JSON_PROPERTY_PATTERN = "pattern";
  private String pattern;

  public static final String JSON_PROPERTY_BRAND = "brand";
  private String brand;

  public static final String JSON_PROPERTY_IS_FAVORITE = "isFavorite";
  private Boolean isFavorite;

  public static final String JSON_PROPERTY_FABRIC = "fabric";
  private String fabric;

  public static final String JSON_PROPERTY_CONDITION = "condition";
  private String condition;

  public static final String JSON_PROPERTY_SLEEVE_LENGTH = "sleeveLength";
  private String sleeveLength;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private String length;

  public static final String JSON_PROPERTY_SIZE_ENUM = "sizeEnum";
  private String sizeEnum;

  public static final String JSON_PROPERTY_PATTERN_DETAIL = "patternDetail";
  private String patternDetail;

  public static final String JSON_PROPERTY_SEASON = "season";
  private List<String> season;

  public static final String JSON_PROPERTY_STYLES = "styles";
  private List<String> styles;

  public static final String JSON_PROPERTY_PHOTO_URI = "photoUri";
  private String photoUri;

  public GarmentDAO() {
  }

  public GarmentDAO garmentId(String garmentId) {
    
    this.garmentId = garmentId;
    return this;
  }

   /**
   * Get garmentId
   * @return garmentId
  **/
   @Nullable
  @JsonProperty(JSON_PROPERTY_GARMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGarmentId() {
    return garmentId;
  }


  @JsonProperty(JSON_PROPERTY_GARMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGarmentId(String garmentId) {
    this.garmentId = garmentId;
  }


  public GarmentDAO photo(GarmentPhotoDAO photo) {
    
    this.photo = photo;
    return this;
  }

   /**
   * Get photo
   * @return photo
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_PHOTO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GarmentPhotoDAO getPhoto() {
    return photo;
  }


  @JsonProperty(JSON_PROPERTY_PHOTO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoto(GarmentPhotoDAO photo) {
    this.photo = photo;
  }


  public GarmentDAO userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  public GarmentDAO title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public GarmentDAO description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public GarmentDAO category(String category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(String category) {
    this.category = category;
  }


  public GarmentDAO subCategory(String subCategory) {
    
    this.subCategory = subCategory;
    return this;
  }

   /**
   * Get subCategory
   * @return subCategory
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_SUB_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubCategory() {
    return subCategory;
  }


  @JsonProperty(JSON_PROPERTY_SUB_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubCategory(String subCategory) {
    this.subCategory = subCategory;
  }


  public GarmentDAO mainColor(String mainColor) {
    
    this.mainColor = mainColor;
    return this;
  }

   /**
   * Get mainColor
   * @return mainColor
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_MAIN_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMainColor() {
    return mainColor;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMainColor(String mainColor) {
    this.mainColor = mainColor;
  }


  public GarmentDAO secondColor(String secondColor) {
    
    this.secondColor = secondColor;
    return this;
  }

   /**
   * Get secondColor
   * @return secondColor
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_SECOND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecondColor() {
    return secondColor;
  }


  @JsonProperty(JSON_PROPERTY_SECOND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondColor(String secondColor) {
    this.secondColor = secondColor;
  }


  public GarmentDAO pattern(String pattern) {
    
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_PATTERN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPattern() {
    return pattern;
  }


  @JsonProperty(JSON_PROPERTY_PATTERN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPattern(String pattern) {
    this.pattern = pattern;
  }


  public GarmentDAO brand(String brand) {
    
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_BRAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrand() {
    return brand;
  }


  @JsonProperty(JSON_PROPERTY_BRAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrand(String brand) {
    this.brand = brand;
  }


  public GarmentDAO isFavorite(Boolean isFavorite) {
    
    this.isFavorite = isFavorite;
    return this;
  }

   /**
   * Get isFavorite
   * @return isFavorite
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsFavorite() {
    return isFavorite;
  }


  @JsonProperty(JSON_PROPERTY_IS_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsFavorite(Boolean isFavorite) {
    this.isFavorite = isFavorite;
  }


  public GarmentDAO fabric(String fabric) {
    
    this.fabric = fabric;
    return this;
  }

   /**
   * Get fabric
   * @return fabric
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_FABRIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFabric() {
    return fabric;
  }


  @JsonProperty(JSON_PROPERTY_FABRIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFabric(String fabric) {
    this.fabric = fabric;
  }


  public GarmentDAO condition(String condition) {
    
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCondition(String condition) {
    this.condition = condition;
  }


  public GarmentDAO sleeveLength(String sleeveLength) {
    
    this.sleeveLength = sleeveLength;
    return this;
  }

   /**
   * Get sleeveLength
   * @return sleeveLength
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_SLEEVE_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSleeveLength() {
    return sleeveLength;
  }


  @JsonProperty(JSON_PROPERTY_SLEEVE_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSleeveLength(String sleeveLength) {
    this.sleeveLength = sleeveLength;
  }


  public GarmentDAO length(String length) {
    
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(String length) {
    this.length = length;
  }


  public GarmentDAO sizeEnum(String sizeEnum) {
    
    this.sizeEnum = sizeEnum;
    return this;
  }

   /**
   * Get sizeEnum
   * @return sizeEnum
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_SIZE_ENUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSizeEnum() {
    return sizeEnum;
  }


  @JsonProperty(JSON_PROPERTY_SIZE_ENUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSizeEnum(String sizeEnum) {
    this.sizeEnum = sizeEnum;
  }


  public GarmentDAO patternDetail(String patternDetail) {
    
    this.patternDetail = patternDetail;
    return this;
  }

   /**
   * Get patternDetail
   * @return patternDetail
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_PATTERN_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPatternDetail() {
    return patternDetail;
  }


  @JsonProperty(JSON_PROPERTY_PATTERN_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPatternDetail(String patternDetail) {
    this.patternDetail = patternDetail;
  }


  public GarmentDAO season(List<String> season) {
    
    this.season = season;
    return this;
  }

  public GarmentDAO addSeasonItem(String seasonItem) {
    if (this.season == null) {
      this.season = new ArrayList<>();
    }
    this.season.add(seasonItem);
    return this;
  }

   /**
   * Get season
   * @return season
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSeason() {
    return season;
  }


  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeason(List<String> season) {
    this.season = season;
  }


  public GarmentDAO styles(List<String> styles) {
    
    this.styles = styles;
    return this;
  }

  public GarmentDAO addStylesItem(String stylesItem) {
    if (this.styles == null) {
      this.styles = new ArrayList<>();
    }
    this.styles.add(stylesItem);
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStyles() {
    return styles;
  }


  @JsonProperty(JSON_PROPERTY_STYLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyles(List<String> styles) {
    this.styles = styles;
  }


  public GarmentDAO photoUri(String photoUri) {
    
    this.photoUri = photoUri;
    return this;
  }

   /**
   * Get photoUri
   * @return photoUri
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_PHOTO_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhotoUri() {
    return photoUri;
  }


  @JsonProperty(JSON_PROPERTY_PHOTO_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhotoUri(String photoUri) {
    this.photoUri = photoUri;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GarmentDAO garmentDAO = (GarmentDAO) o;
    return Objects.equals(this.garmentId, garmentDAO.garmentId) &&
        Objects.equals(this.photo, garmentDAO.photo) &&
        Objects.equals(this.userId, garmentDAO.userId) &&
        Objects.equals(this.title, garmentDAO.title) &&
        Objects.equals(this.description, garmentDAO.description) &&
        Objects.equals(this.category, garmentDAO.category) &&
        Objects.equals(this.subCategory, garmentDAO.subCategory) &&
        Objects.equals(this.mainColor, garmentDAO.mainColor) &&
        Objects.equals(this.secondColor, garmentDAO.secondColor) &&
        Objects.equals(this.pattern, garmentDAO.pattern) &&
        Objects.equals(this.brand, garmentDAO.brand) &&
        Objects.equals(this.isFavorite, garmentDAO.isFavorite) &&
        Objects.equals(this.fabric, garmentDAO.fabric) &&
        Objects.equals(this.condition, garmentDAO.condition) &&
        Objects.equals(this.sleeveLength, garmentDAO.sleeveLength) &&
        Objects.equals(this.length, garmentDAO.length) &&
        Objects.equals(this.sizeEnum, garmentDAO.sizeEnum) &&
        Objects.equals(this.patternDetail, garmentDAO.patternDetail) &&
        Objects.equals(this.season, garmentDAO.season) &&
        Objects.equals(this.styles, garmentDAO.styles) &&
        Objects.equals(this.photoUri, garmentDAO.photoUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(garmentId, photo, userId, title, description, category, subCategory, mainColor, secondColor, pattern, brand, isFavorite, fabric, condition, sleeveLength, length, sizeEnum, patternDetail, season, styles, photoUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GarmentDAO {\n");
    sb.append("    garmentId: ").append(toIndentedString(garmentId)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    subCategory: ").append(toIndentedString(subCategory)).append("\n");
    sb.append("    mainColor: ").append(toIndentedString(mainColor)).append("\n");
    sb.append("    secondColor: ").append(toIndentedString(secondColor)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    isFavorite: ").append(toIndentedString(isFavorite)).append("\n");
    sb.append("    fabric: ").append(toIndentedString(fabric)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    sleeveLength: ").append(toIndentedString(sleeveLength)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    sizeEnum: ").append(toIndentedString(sizeEnum)).append("\n");
    sb.append("    patternDetail: ").append(toIndentedString(patternDetail)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    photoUri: ").append(toIndentedString(photoUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

