spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: "mongodb://root:Glam2023!@localhost:27017/mongodb?authSource=admin"
  ai:
    openai:
      model: "gpt-4-1106-preview"
      apiKey: "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"
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    username: root
    password: Glam2023!
    url: jdbc:mysql://localhost:3306/glam
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  authorization-enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs

logging:
  level:
    com.glam.bff: "DEBUG"
    org.keycloak: info
    org.springframework.web: trace
    org.hibernate: error
    io.milvus: "DEBUG"

server:
  port: 8080
# Temporary disabled for testing
#  servlet:
#    context-path: /resource-server

springdoc:
  swagger-ui:
    path: /swagger

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: glam-admin
      password: glam-admin
    #Temporary disabled for testing
    #realmImportFile: glam-realm.json
  public-client: true
