spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    platform: mysql
    username: avnadmin
    password: AVNS_42BVE8C_PBsEMi_Sxuq
    url: jdbc:mysql://mysql-glam-reply-glam.a.aivencloud.com:10544/glam-db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        #dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger