spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: NON_NULL
  authorization-enabled: false
logging:
  level:
    com.glam.bff: "DEBUG"
    org.keycloak: info
    org.springframework.web: trace
    org.hibernate: error
    io.milvus: "DEBUG"

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger

service:
  glam:
    services:
      user:
        endpoint: "https://user-service.fly.dev"
      wardrobe:
        endpoint: "https://wardrobe-service.fly.dev"
