spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: "mongodb+srv://glam-admin:glam-admin@mongodb-glam.ia09xqm.mongodb.net/glam?retryWrites=true&w=majority"
  ai:
    openai:
      model: "gpt-4-1106-preview"
      apiKey: "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"
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    platform: mysql
    username: avnadmin
    password: AVNS_42BVE8C_PBsEMi_Sxuq
    url: jdbc:mysql://mysql-glam-reply-glam.a.aivencloud.com:10544/glam-db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        #dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  authorization-enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs

logging:
  level:
    com.glam.bff: "DEBUG"
    org.keycloak: info
    org.springframework.web: trace
    org.hibernate: error
    io.milvus: "DEBUG"

server:
  port: 8080
# Temporary disabled for testing
#  servlet:
#    context-path: /resource-server

springdoc:
  swagger-ui:
    path: /swagger

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: glam-admin
      password: glam-admin
    #Temporary disabled for testing
    #realmImportFile: glam-realm.json
  public-client: true
